// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: cms.proto

#ifndef PROTOBUF_cms_2eproto__INCLUDED
#define PROTOBUF_cms_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3000000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3000000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/generated_enum_reflection.h>
#include <google/protobuf/service.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)

namespace cms {

// Internal implementation detail -- do not call these.
void protobuf_AddDesc_cms_2eproto();
void protobuf_AssignDesc_cms_2eproto();
void protobuf_ShutdownFile_cms_2eproto();

class Uuid;
class Order;
class Page;
class Query;
class Filter;
class Response;
class Content;
class ContentList;

enum Response_Level {
  Response_Level_DEBUG = 0,
  Response_Level_INFO = 1,
  Response_Level_WARN = 2,
  Response_Level_ERROR = 3,
  Response_Level_Response_Level_INT_MIN_SENTINEL_DO_NOT_USE_ = ::google::protobuf::kint32min,
  Response_Level_Response_Level_INT_MAX_SENTINEL_DO_NOT_USE_ = ::google::protobuf::kint32max
};
bool Response_Level_IsValid(int value);
const Response_Level Response_Level_Level_MIN = Response_Level_DEBUG;
const Response_Level Response_Level_Level_MAX = Response_Level_ERROR;
const int Response_Level_Level_ARRAYSIZE = Response_Level_Level_MAX + 1;

const ::google::protobuf::EnumDescriptor* Response_Level_descriptor();
inline const ::std::string& Response_Level_Name(Response_Level value) {
  return ::google::protobuf::internal::NameOfEnum(
    Response_Level_descriptor(), value);
}
inline bool Response_Level_Parse(
    const ::std::string& name, Response_Level* value) {
  return ::google::protobuf::internal::ParseNamedEnum<Response_Level>(
    Response_Level_descriptor(), name, value);
}
// ===================================================================

class Uuid : public ::google::protobuf::Message {
 public:
  Uuid();
  virtual ~Uuid();

  Uuid(const Uuid& from);

  inline Uuid& operator=(const Uuid& from) {
    CopyFrom(from);
    return *this;
  }

  inline ::google::protobuf::Arena* GetArena() const { return GetArenaNoVirtual(); }
  inline void* GetMaybeArenaPointer() const {
    return MaybeArenaPtr();
  }
  static const ::google::protobuf::Descriptor* descriptor();
  static const Uuid& default_instance();

  void UnsafeArenaSwap(Uuid* other);
  void Swap(Uuid* other);

  // implements Message ----------------------------------------------

  inline Uuid* New() const { return New(NULL); }

  Uuid* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const Uuid& from);
  void MergeFrom(const Uuid& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(Uuid* other);
  protected:
  explicit Uuid(::google::protobuf::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::google::protobuf::Arena* arena);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional sint64 least_significant_bits = 1;
  void clear_least_significant_bits();
  static const int kLeastSignificantBitsFieldNumber = 1;
  ::google::protobuf::int64 least_significant_bits() const;
  void set_least_significant_bits(::google::protobuf::int64 value);

  // optional sint64 most_significant_bits = 2;
  void clear_most_significant_bits();
  static const int kMostSignificantBitsFieldNumber = 2;
  ::google::protobuf::int64 most_significant_bits() const;
  void set_most_significant_bits(::google::protobuf::int64 value);

  // @@protoc_insertion_point(class_scope:cms.Uuid)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  friend class ::google::protobuf::Arena;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  bool _is_default_instance_;
  ::google::protobuf::int64 least_significant_bits_;
  ::google::protobuf::int64 most_significant_bits_;
  mutable int _cached_size_;
  friend void  protobuf_AddDesc_cms_2eproto();
  friend void protobuf_AssignDesc_cms_2eproto();
  friend void protobuf_ShutdownFile_cms_2eproto();

  void InitAsDefaultInstance();
  static Uuid* default_instance_;
};
// -------------------------------------------------------------------

class Order : public ::google::protobuf::Message {
 public:
  Order();
  virtual ~Order();

  Order(const Order& from);

  inline Order& operator=(const Order& from) {
    CopyFrom(from);
    return *this;
  }

  inline ::google::protobuf::Arena* GetArena() const { return GetArenaNoVirtual(); }
  inline void* GetMaybeArenaPointer() const {
    return MaybeArenaPtr();
  }
  static const ::google::protobuf::Descriptor* descriptor();
  static const Order& default_instance();

  void UnsafeArenaSwap(Order* other);
  void Swap(Order* other);

  // implements Message ----------------------------------------------

  inline Order* New() const { return New(NULL); }

  Order* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const Order& from);
  void MergeFrom(const Order& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(Order* other);
  protected:
  explicit Order(::google::protobuf::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::google::protobuf::Arena* arena);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional bool asc = 1;
  void clear_asc();
  static const int kAscFieldNumber = 1;
  bool asc() const;
  void set_asc(bool value);

  // optional string property = 2;
  void clear_property();
  static const int kPropertyFieldNumber = 2;
  const ::std::string& property() const;
  void set_property(const ::std::string& value);
  void set_property(const char* value);
  void set_property(const char* value, size_t size);
  ::std::string* mutable_property();
  ::std::string* release_property();
  void set_allocated_property(::std::string* property);
  ::std::string* unsafe_arena_release_property();
  void unsafe_arena_set_allocated_property(
      ::std::string* property);

  // @@protoc_insertion_point(class_scope:cms.Order)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  friend class ::google::protobuf::Arena;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  bool _is_default_instance_;
  ::google::protobuf::internal::ArenaStringPtr property_;
  bool asc_;
  mutable int _cached_size_;
  friend void  protobuf_AddDesc_cms_2eproto();
  friend void protobuf_AssignDesc_cms_2eproto();
  friend void protobuf_ShutdownFile_cms_2eproto();

  void InitAsDefaultInstance();
  static Order* default_instance_;
};
// -------------------------------------------------------------------

class Page : public ::google::protobuf::Message {
 public:
  Page();
  virtual ~Page();

  Page(const Page& from);

  inline Page& operator=(const Page& from) {
    CopyFrom(from);
    return *this;
  }

  inline ::google::protobuf::Arena* GetArena() const { return GetArenaNoVirtual(); }
  inline void* GetMaybeArenaPointer() const {
    return MaybeArenaPtr();
  }
  static const ::google::protobuf::Descriptor* descriptor();
  static const Page& default_instance();

  void UnsafeArenaSwap(Page* other);
  void Swap(Page* other);

  // implements Message ----------------------------------------------

  inline Page* New() const { return New(NULL); }

  Page* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const Page& from);
  void MergeFrom(const Page& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(Page* other);
  protected:
  explicit Page(::google::protobuf::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::google::protobuf::Arena* arena);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional uint32 page = 1;
  void clear_page();
  static const int kPageFieldNumber = 1;
  ::google::protobuf::uint32 page() const;
  void set_page(::google::protobuf::uint32 value);

  // optional uint32 elements = 2;
  void clear_elements();
  static const int kElementsFieldNumber = 2;
  ::google::protobuf::uint32 elements() const;
  void set_elements(::google::protobuf::uint32 value);

  // @@protoc_insertion_point(class_scope:cms.Page)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  friend class ::google::protobuf::Arena;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  bool _is_default_instance_;
  ::google::protobuf::uint32 page_;
  ::google::protobuf::uint32 elements_;
  mutable int _cached_size_;
  friend void  protobuf_AddDesc_cms_2eproto();
  friend void protobuf_AssignDesc_cms_2eproto();
  friend void protobuf_ShutdownFile_cms_2eproto();

  void InitAsDefaultInstance();
  static Page* default_instance_;
};
// -------------------------------------------------------------------

class Query : public ::google::protobuf::Message {
 public:
  Query();
  virtual ~Query();

  Query(const Query& from);

  inline Query& operator=(const Query& from) {
    CopyFrom(from);
    return *this;
  }

  inline ::google::protobuf::Arena* GetArena() const { return GetArenaNoVirtual(); }
  inline void* GetMaybeArenaPointer() const {
    return MaybeArenaPtr();
  }
  static const ::google::protobuf::Descriptor* descriptor();
  static const Query& default_instance();

  void UnsafeArenaSwap(Query* other);
  void Swap(Query* other);

  // implements Message ----------------------------------------------

  inline Query* New() const { return New(NULL); }

  Query* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const Query& from);
  void MergeFrom(const Query& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(Query* other);
  protected:
  explicit Query(::google::protobuf::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::google::protobuf::Arena* arena);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated .cms.Order order = 1;
  int order_size() const;
  void clear_order();
  static const int kOrderFieldNumber = 1;
  const ::cms::Order& order(int index) const;
  ::cms::Order* mutable_order(int index);
  ::cms::Order* add_order();
  const ::google::protobuf::RepeatedPtrField< ::cms::Order >&
      order() const;
  ::google::protobuf::RepeatedPtrField< ::cms::Order >*
      mutable_order();

  // repeated .cms.Page page = 2;
  int page_size() const;
  void clear_page();
  static const int kPageFieldNumber = 2;
  const ::cms::Page& page(int index) const;
  ::cms::Page* mutable_page(int index);
  ::cms::Page* add_page();
  const ::google::protobuf::RepeatedPtrField< ::cms::Page >&
      page() const;
  ::google::protobuf::RepeatedPtrField< ::cms::Page >*
      mutable_page();

  // @@protoc_insertion_point(class_scope:cms.Query)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  friend class ::google::protobuf::Arena;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  bool _is_default_instance_;
  ::google::protobuf::RepeatedPtrField< ::cms::Order > order_;
  ::google::protobuf::RepeatedPtrField< ::cms::Page > page_;
  mutable int _cached_size_;
  friend void  protobuf_AddDesc_cms_2eproto();
  friend void protobuf_AssignDesc_cms_2eproto();
  friend void protobuf_ShutdownFile_cms_2eproto();

  void InitAsDefaultInstance();
  static Query* default_instance_;
};
// -------------------------------------------------------------------

class Filter : public ::google::protobuf::Message {
 public:
  Filter();
  virtual ~Filter();

  Filter(const Filter& from);

  inline Filter& operator=(const Filter& from) {
    CopyFrom(from);
    return *this;
  }

  inline ::google::protobuf::Arena* GetArena() const { return GetArenaNoVirtual(); }
  inline void* GetMaybeArenaPointer() const {
    return MaybeArenaPtr();
  }
  static const ::google::protobuf::Descriptor* descriptor();
  static const Filter& default_instance();

  void UnsafeArenaSwap(Filter* other);
  void Swap(Filter* other);

  // implements Message ----------------------------------------------

  inline Filter* New() const { return New(NULL); }

  Filter* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const Filter& from);
  void MergeFrom(const Filter& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(Filter* other);
  protected:
  explicit Filter(::google::protobuf::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::google::protobuf::Arena* arena);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional string by = 1;
  void clear_by();
  static const int kByFieldNumber = 1;
  const ::std::string& by() const;
  void set_by(const ::std::string& value);
  void set_by(const char* value);
  void set_by(const char* value, size_t size);
  ::std::string* mutable_by();
  ::std::string* release_by();
  void set_allocated_by(::std::string* by);
  ::std::string* unsafe_arena_release_by();
  void unsafe_arena_set_allocated_by(
      ::std::string* by);

  // optional .cms.Order order = 2;
  bool has_order() const;
  void clear_order();
  static const int kOrderFieldNumber = 2;
  private:
  void _slow_mutable_order();
  void _slow_set_allocated_order(
      ::google::protobuf::Arena* message_arena, ::cms::Order** order);
  ::cms::Order* _slow_release_order();
  public:
  const ::cms::Order& order() const;
  ::cms::Order* mutable_order();
  ::cms::Order* release_order();
  void set_allocated_order(::cms::Order* order);
  ::cms::Order* unsafe_arena_release_order();
  void unsafe_arena_set_allocated_order(
      ::cms::Order* order);

  // @@protoc_insertion_point(class_scope:cms.Filter)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  friend class ::google::protobuf::Arena;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  bool _is_default_instance_;
  ::google::protobuf::internal::ArenaStringPtr by_;
  ::cms::Order* order_;
  mutable int _cached_size_;
  friend void  protobuf_AddDesc_cms_2eproto();
  friend void protobuf_AssignDesc_cms_2eproto();
  friend void protobuf_ShutdownFile_cms_2eproto();

  void InitAsDefaultInstance();
  static Filter* default_instance_;
};
// -------------------------------------------------------------------

class Response : public ::google::protobuf::Message {
 public:
  Response();
  virtual ~Response();

  Response(const Response& from);

  inline Response& operator=(const Response& from) {
    CopyFrom(from);
    return *this;
  }

  inline ::google::protobuf::Arena* GetArena() const { return GetArenaNoVirtual(); }
  inline void* GetMaybeArenaPointer() const {
    return MaybeArenaPtr();
  }
  static const ::google::protobuf::Descriptor* descriptor();
  static const Response& default_instance();

  void UnsafeArenaSwap(Response* other);
  void Swap(Response* other);

  // implements Message ----------------------------------------------

  inline Response* New() const { return New(NULL); }

  Response* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const Response& from);
  void MergeFrom(const Response& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(Response* other);
  protected:
  explicit Response(::google::protobuf::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::google::protobuf::Arena* arena);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  typedef Response_Level Level;
  static const Level DEBUG = Response_Level_DEBUG;
  static const Level INFO = Response_Level_INFO;
  static const Level WARN = Response_Level_WARN;
  static const Level ERROR = Response_Level_ERROR;
  static inline bool Level_IsValid(int value) {
    return Response_Level_IsValid(value);
  }
  static const Level Level_MIN =
    Response_Level_Level_MIN;
  static const Level Level_MAX =
    Response_Level_Level_MAX;
  static const int Level_ARRAYSIZE =
    Response_Level_Level_ARRAYSIZE;
  static inline const ::google::protobuf::EnumDescriptor*
  Level_descriptor() {
    return Response_Level_descriptor();
  }
  static inline const ::std::string& Level_Name(Level value) {
    return Response_Level_Name(value);
  }
  static inline bool Level_Parse(const ::std::string& name,
      Level* value) {
    return Response_Level_Parse(name, value);
  }

  // accessors -------------------------------------------------------

  // optional string path = 1;
  void clear_path();
  static const int kPathFieldNumber = 1;
  const ::std::string& path() const;
  void set_path(const ::std::string& value);
  void set_path(const char* value);
  void set_path(const char* value, size_t size);
  ::std::string* mutable_path();
  ::std::string* release_path();
  void set_allocated_path(::std::string* path);
  ::std::string* unsafe_arena_release_path();
  void unsafe_arena_set_allocated_path(
      ::std::string* path);

  // optional .cms.Response.Level level = 2;
  void clear_level();
  static const int kLevelFieldNumber = 2;
  ::cms::Response_Level level() const;
  void set_level(::cms::Response_Level value);

  // @@protoc_insertion_point(class_scope:cms.Response)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  friend class ::google::protobuf::Arena;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  bool _is_default_instance_;
  ::google::protobuf::internal::ArenaStringPtr path_;
  int level_;
  mutable int _cached_size_;
  friend void  protobuf_AddDesc_cms_2eproto();
  friend void protobuf_AssignDesc_cms_2eproto();
  friend void protobuf_ShutdownFile_cms_2eproto();

  void InitAsDefaultInstance();
  static Response* default_instance_;
};
// -------------------------------------------------------------------

class Content : public ::google::protobuf::Message {
 public:
  Content();
  virtual ~Content();

  Content(const Content& from);

  inline Content& operator=(const Content& from) {
    CopyFrom(from);
    return *this;
  }

  inline ::google::protobuf::Arena* GetArena() const { return GetArenaNoVirtual(); }
  inline void* GetMaybeArenaPointer() const {
    return MaybeArenaPtr();
  }
  static const ::google::protobuf::Descriptor* descriptor();
  static const Content& default_instance();

  void UnsafeArenaSwap(Content* other);
  void Swap(Content* other);

  // implements Message ----------------------------------------------

  inline Content* New() const { return New(NULL); }

  Content* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const Content& from);
  void MergeFrom(const Content& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(Content* other);
  protected:
  explicit Content(::google::protobuf::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::google::protobuf::Arena* arena);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional .cms.Uuid id = 1;
  bool has_id() const;
  void clear_id();
  static const int kIdFieldNumber = 1;
  private:
  void _slow_mutable_id();
  void _slow_set_allocated_id(
      ::google::protobuf::Arena* message_arena, ::cms::Uuid** id);
  ::cms::Uuid* _slow_release_id();
  public:
  const ::cms::Uuid& id() const;
  ::cms::Uuid* mutable_id();
  ::cms::Uuid* release_id();
  void set_allocated_id(::cms::Uuid* id);
  ::cms::Uuid* unsafe_arena_release_id();
  void unsafe_arena_set_allocated_id(
      ::cms::Uuid* id);

  // optional string title = 2;
  void clear_title();
  static const int kTitleFieldNumber = 2;
  const ::std::string& title() const;
  void set_title(const ::std::string& value);
  void set_title(const char* value);
  void set_title(const char* value, size_t size);
  ::std::string* mutable_title();
  ::std::string* release_title();
  void set_allocated_title(::std::string* title);
  ::std::string* unsafe_arena_release_title();
  void unsafe_arena_set_allocated_title(
      ::std::string* title);

  // optional string description = 3;
  void clear_description();
  static const int kDescriptionFieldNumber = 3;
  const ::std::string& description() const;
  void set_description(const ::std::string& value);
  void set_description(const char* value);
  void set_description(const char* value, size_t size);
  ::std::string* mutable_description();
  ::std::string* release_description();
  void set_allocated_description(::std::string* description);
  ::std::string* unsafe_arena_release_description();
  void unsafe_arena_set_allocated_description(
      ::std::string* description);

  // optional uint32 creation_timestamp = 4;
  void clear_creation_timestamp();
  static const int kCreationTimestampFieldNumber = 4;
  ::google::protobuf::uint32 creation_timestamp() const;
  void set_creation_timestamp(::google::protobuf::uint32 value);

  // optional uint32 updated_timestamp = 5;
  void clear_updated_timestamp();
  static const int kUpdatedTimestampFieldNumber = 5;
  ::google::protobuf::uint32 updated_timestamp() const;
  void set_updated_timestamp(::google::protobuf::uint32 value);

  // @@protoc_insertion_point(class_scope:cms.Content)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  friend class ::google::protobuf::Arena;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  bool _is_default_instance_;
  ::cms::Uuid* id_;
  ::google::protobuf::internal::ArenaStringPtr title_;
  ::google::protobuf::internal::ArenaStringPtr description_;
  ::google::protobuf::uint32 creation_timestamp_;
  ::google::protobuf::uint32 updated_timestamp_;
  mutable int _cached_size_;
  friend void  protobuf_AddDesc_cms_2eproto();
  friend void protobuf_AssignDesc_cms_2eproto();
  friend void protobuf_ShutdownFile_cms_2eproto();

  void InitAsDefaultInstance();
  static Content* default_instance_;
};
// -------------------------------------------------------------------

class ContentList : public ::google::protobuf::Message {
 public:
  ContentList();
  virtual ~ContentList();

  ContentList(const ContentList& from);

  inline ContentList& operator=(const ContentList& from) {
    CopyFrom(from);
    return *this;
  }

  inline ::google::protobuf::Arena* GetArena() const { return GetArenaNoVirtual(); }
  inline void* GetMaybeArenaPointer() const {
    return MaybeArenaPtr();
  }
  static const ::google::protobuf::Descriptor* descriptor();
  static const ContentList& default_instance();

  void UnsafeArenaSwap(ContentList* other);
  void Swap(ContentList* other);

  // implements Message ----------------------------------------------

  inline ContentList* New() const { return New(NULL); }

  ContentList* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const ContentList& from);
  void MergeFrom(const ContentList& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(ContentList* other);
  protected:
  explicit ContentList(::google::protobuf::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::google::protobuf::Arena* arena);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated .cms.Content contents = 1;
  int contents_size() const;
  void clear_contents();
  static const int kContentsFieldNumber = 1;
  const ::cms::Content& contents(int index) const;
  ::cms::Content* mutable_contents(int index);
  ::cms::Content* add_contents();
  const ::google::protobuf::RepeatedPtrField< ::cms::Content >&
      contents() const;
  ::google::protobuf::RepeatedPtrField< ::cms::Content >*
      mutable_contents();

  // @@protoc_insertion_point(class_scope:cms.ContentList)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  friend class ::google::protobuf::Arena;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  bool _is_default_instance_;
  ::google::protobuf::RepeatedPtrField< ::cms::Content > contents_;
  mutable int _cached_size_;
  friend void  protobuf_AddDesc_cms_2eproto();
  friend void protobuf_AssignDesc_cms_2eproto();
  friend void protobuf_ShutdownFile_cms_2eproto();

  void InitAsDefaultInstance();
  static ContentList* default_instance_;
};
// ===================================================================

class CmsCmd_Stub;

class CmsCmd : public ::google::protobuf::Service {
 protected:
  // This class should be treated as an abstract interface.
  inline CmsCmd() {};
 public:
  virtual ~CmsCmd();

  typedef CmsCmd_Stub Stub;

  static const ::google::protobuf::ServiceDescriptor* descriptor();

  virtual void Create(::google::protobuf::RpcController* controller,
                       const ::cms::Content* request,
                       ::cms::Response* response,
                       ::google::protobuf::Closure* done);

  // implements Service ----------------------------------------------

  const ::google::protobuf::ServiceDescriptor* GetDescriptor();
  void CallMethod(const ::google::protobuf::MethodDescriptor* method,
                  ::google::protobuf::RpcController* controller,
                  const ::google::protobuf::Message* request,
                  ::google::protobuf::Message* response,
                  ::google::protobuf::Closure* done);
  const ::google::protobuf::Message& GetRequestPrototype(
    const ::google::protobuf::MethodDescriptor* method) const;
  const ::google::protobuf::Message& GetResponsePrototype(
    const ::google::protobuf::MethodDescriptor* method) const;

 private:
  GOOGLE_DISALLOW_EVIL_CONSTRUCTORS(CmsCmd);
};

class CmsCmd_Stub : public CmsCmd {
 public:
  CmsCmd_Stub(::google::protobuf::RpcChannel* channel);
  CmsCmd_Stub(::google::protobuf::RpcChannel* channel,
                   ::google::protobuf::Service::ChannelOwnership ownership);
  ~CmsCmd_Stub();

  inline ::google::protobuf::RpcChannel* channel() { return channel_; }

  // implements CmsCmd ------------------------------------------

  void Create(::google::protobuf::RpcController* controller,
                       const ::cms::Content* request,
                       ::cms::Response* response,
                       ::google::protobuf::Closure* done);
 private:
  ::google::protobuf::RpcChannel* channel_;
  bool owns_channel_;
  GOOGLE_DISALLOW_EVIL_CONSTRUCTORS(CmsCmd_Stub);
};


// -------------------------------------------------------------------

class CmsQuery_Stub;

class CmsQuery : public ::google::protobuf::Service {
 protected:
  // This class should be treated as an abstract interface.
  inline CmsQuery() {};
 public:
  virtual ~CmsQuery();

  typedef CmsQuery_Stub Stub;

  static const ::google::protobuf::ServiceDescriptor* descriptor();

  virtual void get(::google::protobuf::RpcController* controller,
                       const ::cms::Uuid* request,
                       ::cms::Content* response,
                       ::google::protobuf::Closure* done);
  virtual void get_all(::google::protobuf::RpcController* controller,
                       const ::cms::Query* request,
                       ::cms::ContentList* response,
                       ::google::protobuf::Closure* done);

  // implements Service ----------------------------------------------

  const ::google::protobuf::ServiceDescriptor* GetDescriptor();
  void CallMethod(const ::google::protobuf::MethodDescriptor* method,
                  ::google::protobuf::RpcController* controller,
                  const ::google::protobuf::Message* request,
                  ::google::protobuf::Message* response,
                  ::google::protobuf::Closure* done);
  const ::google::protobuf::Message& GetRequestPrototype(
    const ::google::protobuf::MethodDescriptor* method) const;
  const ::google::protobuf::Message& GetResponsePrototype(
    const ::google::protobuf::MethodDescriptor* method) const;

 private:
  GOOGLE_DISALLOW_EVIL_CONSTRUCTORS(CmsQuery);
};

class CmsQuery_Stub : public CmsQuery {
 public:
  CmsQuery_Stub(::google::protobuf::RpcChannel* channel);
  CmsQuery_Stub(::google::protobuf::RpcChannel* channel,
                   ::google::protobuf::Service::ChannelOwnership ownership);
  ~CmsQuery_Stub();

  inline ::google::protobuf::RpcChannel* channel() { return channel_; }

  // implements CmsQuery ------------------------------------------

  void get(::google::protobuf::RpcController* controller,
                       const ::cms::Uuid* request,
                       ::cms::Content* response,
                       ::google::protobuf::Closure* done);
  void get_all(::google::protobuf::RpcController* controller,
                       const ::cms::Query* request,
                       ::cms::ContentList* response,
                       ::google::protobuf::Closure* done);
 private:
  ::google::protobuf::RpcChannel* channel_;
  bool owns_channel_;
  GOOGLE_DISALLOW_EVIL_CONSTRUCTORS(CmsQuery_Stub);
};


// ===================================================================


// ===================================================================

#if !PROTOBUF_INLINE_NOT_IN_HEADERS
// Uuid

// optional sint64 least_significant_bits = 1;
inline void Uuid::clear_least_significant_bits() {
  least_significant_bits_ = GOOGLE_LONGLONG(0);
}
inline ::google::protobuf::int64 Uuid::least_significant_bits() const {
  // @@protoc_insertion_point(field_get:cms.Uuid.least_significant_bits)
  return least_significant_bits_;
}
inline void Uuid::set_least_significant_bits(::google::protobuf::int64 value) {
  
  least_significant_bits_ = value;
  // @@protoc_insertion_point(field_set:cms.Uuid.least_significant_bits)
}

// optional sint64 most_significant_bits = 2;
inline void Uuid::clear_most_significant_bits() {
  most_significant_bits_ = GOOGLE_LONGLONG(0);
}
inline ::google::protobuf::int64 Uuid::most_significant_bits() const {
  // @@protoc_insertion_point(field_get:cms.Uuid.most_significant_bits)
  return most_significant_bits_;
}
inline void Uuid::set_most_significant_bits(::google::protobuf::int64 value) {
  
  most_significant_bits_ = value;
  // @@protoc_insertion_point(field_set:cms.Uuid.most_significant_bits)
}

// -------------------------------------------------------------------

// Order

// optional bool asc = 1;
inline void Order::clear_asc() {
  asc_ = false;
}
inline bool Order::asc() const {
  // @@protoc_insertion_point(field_get:cms.Order.asc)
  return asc_;
}
inline void Order::set_asc(bool value) {
  
  asc_ = value;
  // @@protoc_insertion_point(field_set:cms.Order.asc)
}

// optional string property = 2;
inline void Order::clear_property() {
  property_.ClearToEmpty(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), GetArenaNoVirtual());
}
inline const ::std::string& Order::property() const {
  // @@protoc_insertion_point(field_get:cms.Order.property)
  return property_.Get(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void Order::set_property(const ::std::string& value) {
  
  property_.Set(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value, GetArenaNoVirtual());
  // @@protoc_insertion_point(field_set:cms.Order.property)
}
inline void Order::set_property(const char* value) {
  
  property_.Set(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value),
              GetArenaNoVirtual());
  // @@protoc_insertion_point(field_set_char:cms.Order.property)
}
inline void Order::set_property(const char* value,
    size_t size) {
  
  property_.Set(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(
      reinterpret_cast<const char*>(value), size), GetArenaNoVirtual());
  // @@protoc_insertion_point(field_set_pointer:cms.Order.property)
}
inline ::std::string* Order::mutable_property() {
  
  // @@protoc_insertion_point(field_mutable:cms.Order.property)
  return property_.Mutable(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), GetArenaNoVirtual());
}
inline ::std::string* Order::release_property() {
  
  return property_.Release(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), GetArenaNoVirtual());
}
inline ::std::string* Order::unsafe_arena_release_property() {
  GOOGLE_DCHECK(GetArenaNoVirtual() != NULL);
  
  return property_.UnsafeArenaRelease(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      GetArenaNoVirtual());
}
inline void Order::set_allocated_property(::std::string* property) {
  if (property != NULL) {
    
  } else {
    
  }
  property_.SetAllocated(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), property,
      GetArenaNoVirtual());
  // @@protoc_insertion_point(field_set_allocated:cms.Order.property)
}
inline void Order::unsafe_arena_set_allocated_property(
    ::std::string* property) {
  GOOGLE_DCHECK(GetArenaNoVirtual() != NULL);
  if (property != NULL) {
    
  } else {
    
  }
  
  property_.UnsafeArenaSetAllocated(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      property, GetArenaNoVirtual());
  // @@protoc_insertion_point(field_set_allocated:cms.Order.property)
}

// -------------------------------------------------------------------

// Page

// optional uint32 page = 1;
inline void Page::clear_page() {
  page_ = 0u;
}
inline ::google::protobuf::uint32 Page::page() const {
  // @@protoc_insertion_point(field_get:cms.Page.page)
  return page_;
}
inline void Page::set_page(::google::protobuf::uint32 value) {
  
  page_ = value;
  // @@protoc_insertion_point(field_set:cms.Page.page)
}

// optional uint32 elements = 2;
inline void Page::clear_elements() {
  elements_ = 0u;
}
inline ::google::protobuf::uint32 Page::elements() const {
  // @@protoc_insertion_point(field_get:cms.Page.elements)
  return elements_;
}
inline void Page::set_elements(::google::protobuf::uint32 value) {
  
  elements_ = value;
  // @@protoc_insertion_point(field_set:cms.Page.elements)
}

// -------------------------------------------------------------------

// Query

// repeated .cms.Order order = 1;
inline int Query::order_size() const {
  return order_.size();
}
inline void Query::clear_order() {
  order_.Clear();
}
inline const ::cms::Order& Query::order(int index) const {
  // @@protoc_insertion_point(field_get:cms.Query.order)
  return order_.Get(index);
}
inline ::cms::Order* Query::mutable_order(int index) {
  // @@protoc_insertion_point(field_mutable:cms.Query.order)
  return order_.Mutable(index);
}
inline ::cms::Order* Query::add_order() {
  // @@protoc_insertion_point(field_add:cms.Query.order)
  return order_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::cms::Order >&
Query::order() const {
  // @@protoc_insertion_point(field_list:cms.Query.order)
  return order_;
}
inline ::google::protobuf::RepeatedPtrField< ::cms::Order >*
Query::mutable_order() {
  // @@protoc_insertion_point(field_mutable_list:cms.Query.order)
  return &order_;
}

// repeated .cms.Page page = 2;
inline int Query::page_size() const {
  return page_.size();
}
inline void Query::clear_page() {
  page_.Clear();
}
inline const ::cms::Page& Query::page(int index) const {
  // @@protoc_insertion_point(field_get:cms.Query.page)
  return page_.Get(index);
}
inline ::cms::Page* Query::mutable_page(int index) {
  // @@protoc_insertion_point(field_mutable:cms.Query.page)
  return page_.Mutable(index);
}
inline ::cms::Page* Query::add_page() {
  // @@protoc_insertion_point(field_add:cms.Query.page)
  return page_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::cms::Page >&
Query::page() const {
  // @@protoc_insertion_point(field_list:cms.Query.page)
  return page_;
}
inline ::google::protobuf::RepeatedPtrField< ::cms::Page >*
Query::mutable_page() {
  // @@protoc_insertion_point(field_mutable_list:cms.Query.page)
  return &page_;
}

// -------------------------------------------------------------------

// Filter

// optional string by = 1;
inline void Filter::clear_by() {
  by_.ClearToEmpty(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), GetArenaNoVirtual());
}
inline const ::std::string& Filter::by() const {
  // @@protoc_insertion_point(field_get:cms.Filter.by)
  return by_.Get(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void Filter::set_by(const ::std::string& value) {
  
  by_.Set(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value, GetArenaNoVirtual());
  // @@protoc_insertion_point(field_set:cms.Filter.by)
}
inline void Filter::set_by(const char* value) {
  
  by_.Set(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value),
              GetArenaNoVirtual());
  // @@protoc_insertion_point(field_set_char:cms.Filter.by)
}
inline void Filter::set_by(const char* value,
    size_t size) {
  
  by_.Set(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(
      reinterpret_cast<const char*>(value), size), GetArenaNoVirtual());
  // @@protoc_insertion_point(field_set_pointer:cms.Filter.by)
}
inline ::std::string* Filter::mutable_by() {
  
  // @@protoc_insertion_point(field_mutable:cms.Filter.by)
  return by_.Mutable(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), GetArenaNoVirtual());
}
inline ::std::string* Filter::release_by() {
  
  return by_.Release(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), GetArenaNoVirtual());
}
inline ::std::string* Filter::unsafe_arena_release_by() {
  GOOGLE_DCHECK(GetArenaNoVirtual() != NULL);
  
  return by_.UnsafeArenaRelease(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      GetArenaNoVirtual());
}
inline void Filter::set_allocated_by(::std::string* by) {
  if (by != NULL) {
    
  } else {
    
  }
  by_.SetAllocated(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), by,
      GetArenaNoVirtual());
  // @@protoc_insertion_point(field_set_allocated:cms.Filter.by)
}
inline void Filter::unsafe_arena_set_allocated_by(
    ::std::string* by) {
  GOOGLE_DCHECK(GetArenaNoVirtual() != NULL);
  if (by != NULL) {
    
  } else {
    
  }
  
  by_.UnsafeArenaSetAllocated(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      by, GetArenaNoVirtual());
  // @@protoc_insertion_point(field_set_allocated:cms.Filter.by)
}

// optional .cms.Order order = 2;
inline bool Filter::has_order() const {
  return !_is_default_instance_ && order_ != NULL;
}
inline void Filter::clear_order() {
  if (order_ != NULL) delete order_;
  order_ = NULL;
}
inline const ::cms::Order& Filter::order() const {
  // @@protoc_insertion_point(field_get:cms.Filter.order)
  return order_ != NULL ? *order_ : *default_instance_->order_;
}
inline ::cms::Order* Filter::mutable_order() {
  
  if (order_ == NULL) {
    _slow_mutable_order();  }
  // @@protoc_insertion_point(field_mutable:cms.Filter.order)
  return order_;
}
inline ::cms::Order* Filter::release_order() {
  
  if (GetArenaNoVirtual() != NULL) {
    return _slow_release_order();
  } else {
    ::cms::Order* temp = order_;
    order_ = NULL;
    return temp;
  }
}
inline void Filter::set_allocated_order(::cms::Order* order) {
  ::google::protobuf::Arena* message_arena = GetArenaNoVirtual();
  if (message_arena == NULL) {
    delete order_;
  }
  if (order != NULL) {
    _slow_set_allocated_order(message_arena, &order);
  }
  order_ = order;
  if (order) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_set_allocated:cms.Filter.order)
}

// -------------------------------------------------------------------

// Response

// optional string path = 1;
inline void Response::clear_path() {
  path_.ClearToEmpty(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), GetArenaNoVirtual());
}
inline const ::std::string& Response::path() const {
  // @@protoc_insertion_point(field_get:cms.Response.path)
  return path_.Get(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void Response::set_path(const ::std::string& value) {
  
  path_.Set(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value, GetArenaNoVirtual());
  // @@protoc_insertion_point(field_set:cms.Response.path)
}
inline void Response::set_path(const char* value) {
  
  path_.Set(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value),
              GetArenaNoVirtual());
  // @@protoc_insertion_point(field_set_char:cms.Response.path)
}
inline void Response::set_path(const char* value,
    size_t size) {
  
  path_.Set(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(
      reinterpret_cast<const char*>(value), size), GetArenaNoVirtual());
  // @@protoc_insertion_point(field_set_pointer:cms.Response.path)
}
inline ::std::string* Response::mutable_path() {
  
  // @@protoc_insertion_point(field_mutable:cms.Response.path)
  return path_.Mutable(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), GetArenaNoVirtual());
}
inline ::std::string* Response::release_path() {
  
  return path_.Release(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), GetArenaNoVirtual());
}
inline ::std::string* Response::unsafe_arena_release_path() {
  GOOGLE_DCHECK(GetArenaNoVirtual() != NULL);
  
  return path_.UnsafeArenaRelease(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      GetArenaNoVirtual());
}
inline void Response::set_allocated_path(::std::string* path) {
  if (path != NULL) {
    
  } else {
    
  }
  path_.SetAllocated(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), path,
      GetArenaNoVirtual());
  // @@protoc_insertion_point(field_set_allocated:cms.Response.path)
}
inline void Response::unsafe_arena_set_allocated_path(
    ::std::string* path) {
  GOOGLE_DCHECK(GetArenaNoVirtual() != NULL);
  if (path != NULL) {
    
  } else {
    
  }
  
  path_.UnsafeArenaSetAllocated(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      path, GetArenaNoVirtual());
  // @@protoc_insertion_point(field_set_allocated:cms.Response.path)
}

// optional .cms.Response.Level level = 2;
inline void Response::clear_level() {
  level_ = 0;
}
inline ::cms::Response_Level Response::level() const {
  // @@protoc_insertion_point(field_get:cms.Response.level)
  return static_cast< ::cms::Response_Level >(level_);
}
inline void Response::set_level(::cms::Response_Level value) {
  
  level_ = value;
  // @@protoc_insertion_point(field_set:cms.Response.level)
}

// -------------------------------------------------------------------

// Content

// optional .cms.Uuid id = 1;
inline bool Content::has_id() const {
  return !_is_default_instance_ && id_ != NULL;
}
inline void Content::clear_id() {
  if (id_ != NULL) delete id_;
  id_ = NULL;
}
inline const ::cms::Uuid& Content::id() const {
  // @@protoc_insertion_point(field_get:cms.Content.id)
  return id_ != NULL ? *id_ : *default_instance_->id_;
}
inline ::cms::Uuid* Content::mutable_id() {
  
  if (id_ == NULL) {
    _slow_mutable_id();  }
  // @@protoc_insertion_point(field_mutable:cms.Content.id)
  return id_;
}
inline ::cms::Uuid* Content::release_id() {
  
  if (GetArenaNoVirtual() != NULL) {
    return _slow_release_id();
  } else {
    ::cms::Uuid* temp = id_;
    id_ = NULL;
    return temp;
  }
}
inline void Content::set_allocated_id(::cms::Uuid* id) {
  ::google::protobuf::Arena* message_arena = GetArenaNoVirtual();
  if (message_arena == NULL) {
    delete id_;
  }
  if (id != NULL) {
    _slow_set_allocated_id(message_arena, &id);
  }
  id_ = id;
  if (id) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_set_allocated:cms.Content.id)
}

// optional string title = 2;
inline void Content::clear_title() {
  title_.ClearToEmpty(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), GetArenaNoVirtual());
}
inline const ::std::string& Content::title() const {
  // @@protoc_insertion_point(field_get:cms.Content.title)
  return title_.Get(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void Content::set_title(const ::std::string& value) {
  
  title_.Set(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value, GetArenaNoVirtual());
  // @@protoc_insertion_point(field_set:cms.Content.title)
}
inline void Content::set_title(const char* value) {
  
  title_.Set(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value),
              GetArenaNoVirtual());
  // @@protoc_insertion_point(field_set_char:cms.Content.title)
}
inline void Content::set_title(const char* value,
    size_t size) {
  
  title_.Set(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(
      reinterpret_cast<const char*>(value), size), GetArenaNoVirtual());
  // @@protoc_insertion_point(field_set_pointer:cms.Content.title)
}
inline ::std::string* Content::mutable_title() {
  
  // @@protoc_insertion_point(field_mutable:cms.Content.title)
  return title_.Mutable(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), GetArenaNoVirtual());
}
inline ::std::string* Content::release_title() {
  
  return title_.Release(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), GetArenaNoVirtual());
}
inline ::std::string* Content::unsafe_arena_release_title() {
  GOOGLE_DCHECK(GetArenaNoVirtual() != NULL);
  
  return title_.UnsafeArenaRelease(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      GetArenaNoVirtual());
}
inline void Content::set_allocated_title(::std::string* title) {
  if (title != NULL) {
    
  } else {
    
  }
  title_.SetAllocated(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), title,
      GetArenaNoVirtual());
  // @@protoc_insertion_point(field_set_allocated:cms.Content.title)
}
inline void Content::unsafe_arena_set_allocated_title(
    ::std::string* title) {
  GOOGLE_DCHECK(GetArenaNoVirtual() != NULL);
  if (title != NULL) {
    
  } else {
    
  }
  
  title_.UnsafeArenaSetAllocated(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      title, GetArenaNoVirtual());
  // @@protoc_insertion_point(field_set_allocated:cms.Content.title)
}

// optional string description = 3;
inline void Content::clear_description() {
  description_.ClearToEmpty(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), GetArenaNoVirtual());
}
inline const ::std::string& Content::description() const {
  // @@protoc_insertion_point(field_get:cms.Content.description)
  return description_.Get(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void Content::set_description(const ::std::string& value) {
  
  description_.Set(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value, GetArenaNoVirtual());
  // @@protoc_insertion_point(field_set:cms.Content.description)
}
inline void Content::set_description(const char* value) {
  
  description_.Set(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value),
              GetArenaNoVirtual());
  // @@protoc_insertion_point(field_set_char:cms.Content.description)
}
inline void Content::set_description(const char* value,
    size_t size) {
  
  description_.Set(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(
      reinterpret_cast<const char*>(value), size), GetArenaNoVirtual());
  // @@protoc_insertion_point(field_set_pointer:cms.Content.description)
}
inline ::std::string* Content::mutable_description() {
  
  // @@protoc_insertion_point(field_mutable:cms.Content.description)
  return description_.Mutable(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), GetArenaNoVirtual());
}
inline ::std::string* Content::release_description() {
  
  return description_.Release(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), GetArenaNoVirtual());
}
inline ::std::string* Content::unsafe_arena_release_description() {
  GOOGLE_DCHECK(GetArenaNoVirtual() != NULL);
  
  return description_.UnsafeArenaRelease(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      GetArenaNoVirtual());
}
inline void Content::set_allocated_description(::std::string* description) {
  if (description != NULL) {
    
  } else {
    
  }
  description_.SetAllocated(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), description,
      GetArenaNoVirtual());
  // @@protoc_insertion_point(field_set_allocated:cms.Content.description)
}
inline void Content::unsafe_arena_set_allocated_description(
    ::std::string* description) {
  GOOGLE_DCHECK(GetArenaNoVirtual() != NULL);
  if (description != NULL) {
    
  } else {
    
  }
  
  description_.UnsafeArenaSetAllocated(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      description, GetArenaNoVirtual());
  // @@protoc_insertion_point(field_set_allocated:cms.Content.description)
}

// optional uint32 creation_timestamp = 4;
inline void Content::clear_creation_timestamp() {
  creation_timestamp_ = 0u;
}
inline ::google::protobuf::uint32 Content::creation_timestamp() const {
  // @@protoc_insertion_point(field_get:cms.Content.creation_timestamp)
  return creation_timestamp_;
}
inline void Content::set_creation_timestamp(::google::protobuf::uint32 value) {
  
  creation_timestamp_ = value;
  // @@protoc_insertion_point(field_set:cms.Content.creation_timestamp)
}

// optional uint32 updated_timestamp = 5;
inline void Content::clear_updated_timestamp() {
  updated_timestamp_ = 0u;
}
inline ::google::protobuf::uint32 Content::updated_timestamp() const {
  // @@protoc_insertion_point(field_get:cms.Content.updated_timestamp)
  return updated_timestamp_;
}
inline void Content::set_updated_timestamp(::google::protobuf::uint32 value) {
  
  updated_timestamp_ = value;
  // @@protoc_insertion_point(field_set:cms.Content.updated_timestamp)
}

// -------------------------------------------------------------------

// ContentList

// repeated .cms.Content contents = 1;
inline int ContentList::contents_size() const {
  return contents_.size();
}
inline void ContentList::clear_contents() {
  contents_.Clear();
}
inline const ::cms::Content& ContentList::contents(int index) const {
  // @@protoc_insertion_point(field_get:cms.ContentList.contents)
  return contents_.Get(index);
}
inline ::cms::Content* ContentList::mutable_contents(int index) {
  // @@protoc_insertion_point(field_mutable:cms.ContentList.contents)
  return contents_.Mutable(index);
}
inline ::cms::Content* ContentList::add_contents() {
  // @@protoc_insertion_point(field_add:cms.ContentList.contents)
  return contents_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::cms::Content >&
ContentList::contents() const {
  // @@protoc_insertion_point(field_list:cms.ContentList.contents)
  return contents_;
}
inline ::google::protobuf::RepeatedPtrField< ::cms::Content >*
ContentList::mutable_contents() {
  // @@protoc_insertion_point(field_mutable_list:cms.ContentList.contents)
  return &contents_;
}

#endif  // !PROTOBUF_INLINE_NOT_IN_HEADERS

// @@protoc_insertion_point(namespace_scope)

}  // namespace cms

#ifndef SWIG
namespace google {
namespace protobuf {

template <> struct is_proto_enum< ::cms::Response_Level> : ::google::protobuf::internal::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::cms::Response_Level>() {
  return ::cms::Response_Level_descriptor();
}

}  // namespace protobuf
}  // namespace google
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_cms_2eproto__INCLUDED
