// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: content.proto

#ifndef PROTOBUF_content_2eproto__INCLUDED
#define PROTOBUF_content_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3000000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3000000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/generated_enum_reflection.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)

namespace content {

// Internal implementation detail -- do not call these.
void protobuf_AddDesc_content_2eproto();
void protobuf_AssignDesc_content_2eproto();
void protobuf_ShutdownFile_content_2eproto();

class Uuid;
class ContentData;
class ContentPart;
class Content;
class CmdResponse;
class UpdatePart;

enum Format {
  HTML = 0,
  MD = 1,
  RST = 2,
  SRC = 3,
  IMG = 4,
  GIST = 5,
  Format_INT_MIN_SENTINEL_DO_NOT_USE_ = ::google::protobuf::kint32min,
  Format_INT_MAX_SENTINEL_DO_NOT_USE_ = ::google::protobuf::kint32max
};
bool Format_IsValid(int value);
const Format Format_MIN = HTML;
const Format Format_MAX = GIST;
const int Format_ARRAYSIZE = Format_MAX + 1;

const ::google::protobuf::EnumDescriptor* Format_descriptor();
inline const ::std::string& Format_Name(Format value) {
  return ::google::protobuf::internal::NameOfEnum(
    Format_descriptor(), value);
}
inline bool Format_Parse(
    const ::std::string& name, Format* value) {
  return ::google::protobuf::internal::ParseNamedEnum<Format>(
    Format_descriptor(), name, value);
}
enum Level {
  DEBUG = 0,
  INFO = 1,
  WARN = 2,
  ERROR = 3,
  Level_INT_MIN_SENTINEL_DO_NOT_USE_ = ::google::protobuf::kint32min,
  Level_INT_MAX_SENTINEL_DO_NOT_USE_ = ::google::protobuf::kint32max
};
bool Level_IsValid(int value);
const Level Level_MIN = DEBUG;
const Level Level_MAX = ERROR;
const int Level_ARRAYSIZE = Level_MAX + 1;

const ::google::protobuf::EnumDescriptor* Level_descriptor();
inline const ::std::string& Level_Name(Level value) {
  return ::google::protobuf::internal::NameOfEnum(
    Level_descriptor(), value);
}
inline bool Level_Parse(
    const ::std::string& name, Level* value) {
  return ::google::protobuf::internal::ParseNamedEnum<Level>(
    Level_descriptor(), name, value);
}
// ===================================================================

class Uuid : public ::google::protobuf::Message {
 public:
  Uuid();
  virtual ~Uuid();

  Uuid(const Uuid& from);

  inline Uuid& operator=(const Uuid& from) {
    CopyFrom(from);
    return *this;
  }

  inline ::google::protobuf::Arena* GetArena() const { return GetArenaNoVirtual(); }
  inline void* GetMaybeArenaPointer() const {
    return MaybeArenaPtr();
  }
  static const ::google::protobuf::Descriptor* descriptor();
  static const Uuid& default_instance();

  void UnsafeArenaSwap(Uuid* other);
  void Swap(Uuid* other);

  // implements Message ----------------------------------------------

  inline Uuid* New() const { return New(NULL); }

  Uuid* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const Uuid& from);
  void MergeFrom(const Uuid& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(Uuid* other);
  protected:
  explicit Uuid(::google::protobuf::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::google::protobuf::Arena* arena);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional sint64 least_significant_bits = 1;
  inline void clear_least_significant_bits();
  static const int kLeastSignificantBitsFieldNumber = 1;
  inline ::google::protobuf::int64 least_significant_bits() const;
  inline void set_least_significant_bits(::google::protobuf::int64 value);

  // optional sint64 most_significant_bits = 2;
  inline void clear_most_significant_bits();
  static const int kMostSignificantBitsFieldNumber = 2;
  inline ::google::protobuf::int64 most_significant_bits() const;
  inline void set_most_significant_bits(::google::protobuf::int64 value);

  // @@protoc_insertion_point(class_scope:content.Uuid)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  friend class ::google::protobuf::Arena;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  bool _is_default_instance_;
  ::google::protobuf::int64 least_significant_bits_;
  ::google::protobuf::int64 most_significant_bits_;
  mutable int _cached_size_;
  friend void  protobuf_AddDesc_content_2eproto();
  friend void protobuf_AssignDesc_content_2eproto();
  friend void protobuf_ShutdownFile_content_2eproto();

  void InitAsDefaultInstance();
  static Uuid* default_instance_;
};
// -------------------------------------------------------------------

class ContentData : public ::google::protobuf::Message {
 public:
  ContentData();
  virtual ~ContentData();

  ContentData(const ContentData& from);

  inline ContentData& operator=(const ContentData& from) {
    CopyFrom(from);
    return *this;
  }

  inline ::google::protobuf::Arena* GetArena() const { return GetArenaNoVirtual(); }
  inline void* GetMaybeArenaPointer() const {
    return MaybeArenaPtr();
  }
  static const ::google::protobuf::Descriptor* descriptor();
  static const ContentData& default_instance();

  void UnsafeArenaSwap(ContentData* other);
  void Swap(ContentData* other);

  // implements Message ----------------------------------------------

  inline ContentData* New() const { return New(NULL); }

  ContentData* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const ContentData& from);
  void MergeFrom(const ContentData& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(ContentData* other);
  protected:
  explicit ContentData(::google::protobuf::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::google::protobuf::Arena* arena);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional .content.Uuid id = 1;
  inline bool has_id() const;
  inline void clear_id();
  static const int kIdFieldNumber = 1;
  inline const ::content::Uuid& id() const;
  inline ::content::Uuid* mutable_id();
  inline ::content::Uuid* release_id();
  inline void set_allocated_id(::content::Uuid* id);
  inline ::content::Uuid* unsafe_arena_release_id();
  inline void unsafe_arena_set_allocated_id(
      ::content::Uuid* id);

  // optional string title = 2;
  inline void clear_title();
  static const int kTitleFieldNumber = 2;
  inline const ::std::string& title() const;
  inline void set_title(const ::std::string& value);
  inline void set_title(const char* value);
  inline void set_title(const char* value, size_t size);
  inline ::std::string* mutable_title();
  inline ::std::string* release_title();
  inline void set_allocated_title(::std::string* title);
  inline ::std::string* unsafe_arena_release_title();
  inline void unsafe_arena_set_allocated_title(
      ::std::string* title);

  // repeated .content.Uuid authors = 3;
  inline int authors_size() const;
  inline void clear_authors();
  static const int kAuthorsFieldNumber = 3;
  inline const ::content::Uuid& authors(int index) const;
  inline ::content::Uuid* mutable_authors(int index);
  inline ::content::Uuid* add_authors();
  inline const ::google::protobuf::RepeatedPtrField< ::content::Uuid >&
      authors() const;
  inline ::google::protobuf::RepeatedPtrField< ::content::Uuid >*
      mutable_authors();

  // @@protoc_insertion_point(class_scope:content.ContentData)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  friend class ::google::protobuf::Arena;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  bool _is_default_instance_;
  ::content::Uuid* id_;
  ::google::protobuf::internal::ArenaStringPtr title_;
  ::google::protobuf::RepeatedPtrField< ::content::Uuid > authors_;
  mutable int _cached_size_;
  friend void  protobuf_AddDesc_content_2eproto();
  friend void protobuf_AssignDesc_content_2eproto();
  friend void protobuf_ShutdownFile_content_2eproto();

  void InitAsDefaultInstance();
  static ContentData* default_instance_;
};
// -------------------------------------------------------------------

class ContentPart : public ::google::protobuf::Message {
 public:
  ContentPart();
  virtual ~ContentPart();

  ContentPart(const ContentPart& from);

  inline ContentPart& operator=(const ContentPart& from) {
    CopyFrom(from);
    return *this;
  }

  inline ::google::protobuf::Arena* GetArena() const { return GetArenaNoVirtual(); }
  inline void* GetMaybeArenaPointer() const {
    return MaybeArenaPtr();
  }
  static const ::google::protobuf::Descriptor* descriptor();
  static const ContentPart& default_instance();

  void UnsafeArenaSwap(ContentPart* other);
  void Swap(ContentPart* other);

  // implements Message ----------------------------------------------

  inline ContentPart* New() const { return New(NULL); }

  ContentPart* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const ContentPart& from);
  void MergeFrom(const ContentPart& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(ContentPart* other);
  protected:
  explicit ContentPart(::google::protobuf::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::google::protobuf::Arena* arena);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional .content.ContentData info = 1;
  inline bool has_info() const;
  inline void clear_info();
  static const int kInfoFieldNumber = 1;
  inline const ::content::ContentData& info() const;
  inline ::content::ContentData* mutable_info();
  inline ::content::ContentData* release_info();
  inline void set_allocated_info(::content::ContentData* info);
  inline ::content::ContentData* unsafe_arena_release_info();
  inline void unsafe_arena_set_allocated_info(
      ::content::ContentData* info);

  // optional .content.Format format = 2;
  inline void clear_format();
  static const int kFormatFieldNumber = 2;
  inline ::content::Format format() const;
  inline void set_format(::content::Format value);

  // optional string data = 3;
  inline void clear_data();
  static const int kDataFieldNumber = 3;
  inline const ::std::string& data() const;
  inline void set_data(const ::std::string& value);
  inline void set_data(const char* value);
  inline void set_data(const char* value, size_t size);
  inline ::std::string* mutable_data();
  inline ::std::string* release_data();
  inline void set_allocated_data(::std::string* data);
  inline ::std::string* unsafe_arena_release_data();
  inline void unsafe_arena_set_allocated_data(
      ::std::string* data);

  // @@protoc_insertion_point(class_scope:content.ContentPart)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  friend class ::google::protobuf::Arena;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  bool _is_default_instance_;
  ::content::ContentData* info_;
  ::google::protobuf::internal::ArenaStringPtr data_;
  int format_;
  mutable int _cached_size_;
  friend void  protobuf_AddDesc_content_2eproto();
  friend void protobuf_AssignDesc_content_2eproto();
  friend void protobuf_ShutdownFile_content_2eproto();

  void InitAsDefaultInstance();
  static ContentPart* default_instance_;
};
// -------------------------------------------------------------------

class Content : public ::google::protobuf::Message {
 public:
  Content();
  virtual ~Content();

  Content(const Content& from);

  inline Content& operator=(const Content& from) {
    CopyFrom(from);
    return *this;
  }

  inline ::google::protobuf::Arena* GetArena() const { return GetArenaNoVirtual(); }
  inline void* GetMaybeArenaPointer() const {
    return MaybeArenaPtr();
  }
  static const ::google::protobuf::Descriptor* descriptor();
  static const Content& default_instance();

  void UnsafeArenaSwap(Content* other);
  void Swap(Content* other);

  // implements Message ----------------------------------------------

  inline Content* New() const { return New(NULL); }

  Content* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const Content& from);
  void MergeFrom(const Content& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(Content* other);
  protected:
  explicit Content(::google::protobuf::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::google::protobuf::Arena* arena);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional .content.ContentData info = 1;
  inline bool has_info() const;
  inline void clear_info();
  static const int kInfoFieldNumber = 1;
  inline const ::content::ContentData& info() const;
  inline ::content::ContentData* mutable_info();
  inline ::content::ContentData* release_info();
  inline void set_allocated_info(::content::ContentData* info);
  inline ::content::ContentData* unsafe_arena_release_info();
  inline void unsafe_arena_set_allocated_info(
      ::content::ContentData* info);

  // repeated .content.ContentPart parts = 2;
  inline int parts_size() const;
  inline void clear_parts();
  static const int kPartsFieldNumber = 2;
  inline const ::content::ContentPart& parts(int index) const;
  inline ::content::ContentPart* mutable_parts(int index);
  inline ::content::ContentPart* add_parts();
  inline const ::google::protobuf::RepeatedPtrField< ::content::ContentPart >&
      parts() const;
  inline ::google::protobuf::RepeatedPtrField< ::content::ContentPart >*
      mutable_parts();

  // @@protoc_insertion_point(class_scope:content.Content)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  friend class ::google::protobuf::Arena;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  bool _is_default_instance_;
  ::content::ContentData* info_;
  ::google::protobuf::RepeatedPtrField< ::content::ContentPart > parts_;
  mutable int _cached_size_;
  friend void  protobuf_AddDesc_content_2eproto();
  friend void protobuf_AssignDesc_content_2eproto();
  friend void protobuf_ShutdownFile_content_2eproto();

  void InitAsDefaultInstance();
  static Content* default_instance_;
};
// -------------------------------------------------------------------

class CmdResponse : public ::google::protobuf::Message {
 public:
  CmdResponse();
  virtual ~CmdResponse();

  CmdResponse(const CmdResponse& from);

  inline CmdResponse& operator=(const CmdResponse& from) {
    CopyFrom(from);
    return *this;
  }

  inline ::google::protobuf::Arena* GetArena() const { return GetArenaNoVirtual(); }
  inline void* GetMaybeArenaPointer() const {
    return MaybeArenaPtr();
  }
  static const ::google::protobuf::Descriptor* descriptor();
  static const CmdResponse& default_instance();

  void UnsafeArenaSwap(CmdResponse* other);
  void Swap(CmdResponse* other);

  // implements Message ----------------------------------------------

  inline CmdResponse* New() const { return New(NULL); }

  CmdResponse* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const CmdResponse& from);
  void MergeFrom(const CmdResponse& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(CmdResponse* other);
  protected:
  explicit CmdResponse(::google::protobuf::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::google::protobuf::Arena* arena);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional string path = 1;
  inline void clear_path();
  static const int kPathFieldNumber = 1;
  inline const ::std::string& path() const;
  inline void set_path(const ::std::string& value);
  inline void set_path(const char* value);
  inline void set_path(const char* value, size_t size);
  inline ::std::string* mutable_path();
  inline ::std::string* release_path();
  inline void set_allocated_path(::std::string* path);
  inline ::std::string* unsafe_arena_release_path();
  inline void unsafe_arena_set_allocated_path(
      ::std::string* path);

  // optional .content.Level level = 2;
  inline void clear_level();
  static const int kLevelFieldNumber = 2;
  inline ::content::Level level() const;
  inline void set_level(::content::Level value);

  // optional string msg = 3;
  inline void clear_msg();
  static const int kMsgFieldNumber = 3;
  inline const ::std::string& msg() const;
  inline void set_msg(const ::std::string& value);
  inline void set_msg(const char* value);
  inline void set_msg(const char* value, size_t size);
  inline ::std::string* mutable_msg();
  inline ::std::string* release_msg();
  inline void set_allocated_msg(::std::string* msg);
  inline ::std::string* unsafe_arena_release_msg();
  inline void unsafe_arena_set_allocated_msg(
      ::std::string* msg);

  // @@protoc_insertion_point(class_scope:content.CmdResponse)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  friend class ::google::protobuf::Arena;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  bool _is_default_instance_;
  ::google::protobuf::internal::ArenaStringPtr path_;
  ::google::protobuf::internal::ArenaStringPtr msg_;
  int level_;
  mutable int _cached_size_;
  friend void  protobuf_AddDesc_content_2eproto();
  friend void protobuf_AssignDesc_content_2eproto();
  friend void protobuf_ShutdownFile_content_2eproto();

  void InitAsDefaultInstance();
  static CmdResponse* default_instance_;
};
// -------------------------------------------------------------------

class UpdatePart : public ::google::protobuf::Message {
 public:
  UpdatePart();
  virtual ~UpdatePart();

  UpdatePart(const UpdatePart& from);

  inline UpdatePart& operator=(const UpdatePart& from) {
    CopyFrom(from);
    return *this;
  }

  inline ::google::protobuf::Arena* GetArena() const { return GetArenaNoVirtual(); }
  inline void* GetMaybeArenaPointer() const {
    return MaybeArenaPtr();
  }
  static const ::google::protobuf::Descriptor* descriptor();
  static const UpdatePart& default_instance();

  void UnsafeArenaSwap(UpdatePart* other);
  void Swap(UpdatePart* other);

  // implements Message ----------------------------------------------

  inline UpdatePart* New() const { return New(NULL); }

  UpdatePart* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const UpdatePart& from);
  void MergeFrom(const UpdatePart& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(UpdatePart* other);
  protected:
  explicit UpdatePart(::google::protobuf::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::google::protobuf::Arena* arena);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional .content.ContentPart part = 1;
  inline bool has_part() const;
  inline void clear_part();
  static const int kPartFieldNumber = 1;
  inline const ::content::ContentPart& part() const;
  inline ::content::ContentPart* mutable_part();
  inline ::content::ContentPart* release_part();
  inline void set_allocated_part(::content::ContentPart* part);
  inline ::content::ContentPart* unsafe_arena_release_part();
  inline void unsafe_arena_set_allocated_part(
      ::content::ContentPart* part);

  // optional uint32 position = 2;
  inline void clear_position();
  static const int kPositionFieldNumber = 2;
  inline ::google::protobuf::uint32 position() const;
  inline void set_position(::google::protobuf::uint32 value);

  // @@protoc_insertion_point(class_scope:content.UpdatePart)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  friend class ::google::protobuf::Arena;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  bool _is_default_instance_;
  ::content::ContentPart* part_;
  ::google::protobuf::uint32 position_;
  mutable int _cached_size_;
  friend void  protobuf_AddDesc_content_2eproto();
  friend void protobuf_AssignDesc_content_2eproto();
  friend void protobuf_ShutdownFile_content_2eproto();

  void InitAsDefaultInstance();
  static UpdatePart* default_instance_;
};
// ===================================================================


// ===================================================================

// Uuid

// optional sint64 least_significant_bits = 1;
inline void Uuid::clear_least_significant_bits() {
  least_significant_bits_ = GOOGLE_LONGLONG(0);
}
inline ::google::protobuf::int64 Uuid::least_significant_bits() const {
  // @@protoc_insertion_point(field_get:content.Uuid.least_significant_bits)
  return least_significant_bits_;
}
inline void Uuid::set_least_significant_bits(::google::protobuf::int64 value) {
  
  least_significant_bits_ = value;
  // @@protoc_insertion_point(field_set:content.Uuid.least_significant_bits)
}

// optional sint64 most_significant_bits = 2;
inline void Uuid::clear_most_significant_bits() {
  most_significant_bits_ = GOOGLE_LONGLONG(0);
}
inline ::google::protobuf::int64 Uuid::most_significant_bits() const {
  // @@protoc_insertion_point(field_get:content.Uuid.most_significant_bits)
  return most_significant_bits_;
}
inline void Uuid::set_most_significant_bits(::google::protobuf::int64 value) {
  
  most_significant_bits_ = value;
  // @@protoc_insertion_point(field_set:content.Uuid.most_significant_bits)
}

// -------------------------------------------------------------------

// ContentData

// optional .content.Uuid id = 1;
inline bool ContentData::has_id() const {
  return !_is_default_instance_ && id_ != NULL;
}
inline void ContentData::clear_id() {
  if (id_ != NULL) delete id_;
  id_ = NULL;
}
inline const ::content::Uuid& ContentData::id() const {
  // @@protoc_insertion_point(field_get:content.ContentData.id)
  return id_ != NULL ? *id_ : *default_instance_->id_;
}
inline ::content::Uuid* ContentData::mutable_id() {
  
  if (id_ == NULL) {
    id_ = ::google::protobuf::Arena::CreateMessage< ::content::Uuid >(
        GetArenaNoVirtual());
  }
  // @@protoc_insertion_point(field_mutable:content.ContentData.id)
  return id_;
}
inline ::content::Uuid* ContentData::release_id() {
  
  if (GetArenaNoVirtual() != NULL) {
    if (id_ == NULL) {
      return NULL;
    } else {
      ::content::Uuid* temp = new ::content::Uuid;
      temp->MergeFrom(*id_);
      id_ = NULL;
      return temp;
    }
  } else {
    ::content::Uuid* temp = id_;
    id_ = NULL;
    return temp;
  }
}
inline ::content::Uuid* ContentData::unsafe_arena_release_id() {
  
  ::content::Uuid* temp = id_;
  id_ = NULL;
  return temp;
}
inline void ContentData::set_allocated_id(::content::Uuid* id) {
  if (GetArenaNoVirtual() == NULL) {
    delete id_;
  }
  if (id != NULL) {
    if (GetArenaNoVirtual() != NULL && 
        ::google::protobuf::Arena::GetArena(id) == NULL) {
      GetArenaNoVirtual()->Own(id);
    } else if (GetArenaNoVirtual() !=
               ::google::protobuf::Arena::GetArena(id)) {
      ::content::Uuid* new_id = 
            ::google::protobuf::Arena::CreateMessage< ::content::Uuid >(
            GetArenaNoVirtual());
      new_id->CopyFrom(*id);
      id = new_id;
    }
  }
  id_ = id;
  if (id) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_set_allocated:content.ContentData.id)
}
inline void ContentData::unsafe_arena_set_allocated_id(
    ::content::Uuid* id) {
  if (GetArenaNoVirtual() == NULL) {
    delete id_;
  }
  id_ = id;
  if (id) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:content.ContentData.id)
}

// optional string title = 2;
inline void ContentData::clear_title() {
  title_.ClearToEmpty(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), GetArenaNoVirtual());
}
inline const ::std::string& ContentData::title() const {
  // @@protoc_insertion_point(field_get:content.ContentData.title)
  return title_.Get(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void ContentData::set_title(const ::std::string& value) {
  
  title_.Set(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value, GetArenaNoVirtual());
  // @@protoc_insertion_point(field_set:content.ContentData.title)
}
inline void ContentData::set_title(const char* value) {
  
  title_.Set(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value),
              GetArenaNoVirtual());
  // @@protoc_insertion_point(field_set_char:content.ContentData.title)
}
inline void ContentData::set_title(const char* value,
    size_t size) {
  
  title_.Set(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(
      reinterpret_cast<const char*>(value), size), GetArenaNoVirtual());
  // @@protoc_insertion_point(field_set_pointer:content.ContentData.title)
}
inline ::std::string* ContentData::mutable_title() {
  
  // @@protoc_insertion_point(field_mutable:content.ContentData.title)
  return title_.Mutable(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), GetArenaNoVirtual());
}
inline ::std::string* ContentData::release_title() {
  
  return title_.Release(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), GetArenaNoVirtual());
}
inline ::std::string* ContentData::unsafe_arena_release_title() {
  GOOGLE_DCHECK(GetArenaNoVirtual() != NULL);
  
  return title_.UnsafeArenaRelease(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      GetArenaNoVirtual());
}
inline void ContentData::set_allocated_title(::std::string* title) {
  if (title != NULL) {
    
  } else {
    
  }
  title_.SetAllocated(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), title,
      GetArenaNoVirtual());
  // @@protoc_insertion_point(field_set_allocated:content.ContentData.title)
}
inline void ContentData::unsafe_arena_set_allocated_title(
    ::std::string* title) {
  GOOGLE_DCHECK(GetArenaNoVirtual() != NULL);
  if (title != NULL) {
    
  } else {
    
  }
  
  title_.UnsafeArenaSetAllocated(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      title, GetArenaNoVirtual());
  // @@protoc_insertion_point(field_set_allocated:content.ContentData.title)
}

// repeated .content.Uuid authors = 3;
inline int ContentData::authors_size() const {
  return authors_.size();
}
inline void ContentData::clear_authors() {
  authors_.Clear();
}
inline const ::content::Uuid& ContentData::authors(int index) const {
  // @@protoc_insertion_point(field_get:content.ContentData.authors)
  return authors_.Get(index);
}
inline ::content::Uuid* ContentData::mutable_authors(int index) {
  // @@protoc_insertion_point(field_mutable:content.ContentData.authors)
  return authors_.Mutable(index);
}
inline ::content::Uuid* ContentData::add_authors() {
  // @@protoc_insertion_point(field_add:content.ContentData.authors)
  return authors_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::content::Uuid >&
ContentData::authors() const {
  // @@protoc_insertion_point(field_list:content.ContentData.authors)
  return authors_;
}
inline ::google::protobuf::RepeatedPtrField< ::content::Uuid >*
ContentData::mutable_authors() {
  // @@protoc_insertion_point(field_mutable_list:content.ContentData.authors)
  return &authors_;
}

// -------------------------------------------------------------------

// ContentPart

// optional .content.ContentData info = 1;
inline bool ContentPart::has_info() const {
  return !_is_default_instance_ && info_ != NULL;
}
inline void ContentPart::clear_info() {
  if (info_ != NULL) delete info_;
  info_ = NULL;
}
inline const ::content::ContentData& ContentPart::info() const {
  // @@protoc_insertion_point(field_get:content.ContentPart.info)
  return info_ != NULL ? *info_ : *default_instance_->info_;
}
inline ::content::ContentData* ContentPart::mutable_info() {
  
  if (info_ == NULL) {
    info_ = ::google::protobuf::Arena::CreateMessage< ::content::ContentData >(
        GetArenaNoVirtual());
  }
  // @@protoc_insertion_point(field_mutable:content.ContentPart.info)
  return info_;
}
inline ::content::ContentData* ContentPart::release_info() {
  
  if (GetArenaNoVirtual() != NULL) {
    if (info_ == NULL) {
      return NULL;
    } else {
      ::content::ContentData* temp = new ::content::ContentData;
      temp->MergeFrom(*info_);
      info_ = NULL;
      return temp;
    }
  } else {
    ::content::ContentData* temp = info_;
    info_ = NULL;
    return temp;
  }
}
inline ::content::ContentData* ContentPart::unsafe_arena_release_info() {
  
  ::content::ContentData* temp = info_;
  info_ = NULL;
  return temp;
}
inline void ContentPart::set_allocated_info(::content::ContentData* info) {
  if (GetArenaNoVirtual() == NULL) {
    delete info_;
  }
  if (info != NULL) {
    if (GetArenaNoVirtual() != NULL && 
        ::google::protobuf::Arena::GetArena(info) == NULL) {
      GetArenaNoVirtual()->Own(info);
    } else if (GetArenaNoVirtual() !=
               ::google::protobuf::Arena::GetArena(info)) {
      ::content::ContentData* new_info = 
            ::google::protobuf::Arena::CreateMessage< ::content::ContentData >(
            GetArenaNoVirtual());
      new_info->CopyFrom(*info);
      info = new_info;
    }
  }
  info_ = info;
  if (info) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_set_allocated:content.ContentPart.info)
}
inline void ContentPart::unsafe_arena_set_allocated_info(
    ::content::ContentData* info) {
  if (GetArenaNoVirtual() == NULL) {
    delete info_;
  }
  info_ = info;
  if (info) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:content.ContentPart.info)
}

// optional .content.Format format = 2;
inline void ContentPart::clear_format() {
  format_ = 0;
}
inline ::content::Format ContentPart::format() const {
  // @@protoc_insertion_point(field_get:content.ContentPart.format)
  return static_cast< ::content::Format >(format_);
}
inline void ContentPart::set_format(::content::Format value) {
  
  format_ = value;
  // @@protoc_insertion_point(field_set:content.ContentPart.format)
}

// optional string data = 3;
inline void ContentPart::clear_data() {
  data_.ClearToEmpty(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), GetArenaNoVirtual());
}
inline const ::std::string& ContentPart::data() const {
  // @@protoc_insertion_point(field_get:content.ContentPart.data)
  return data_.Get(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void ContentPart::set_data(const ::std::string& value) {
  
  data_.Set(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value, GetArenaNoVirtual());
  // @@protoc_insertion_point(field_set:content.ContentPart.data)
}
inline void ContentPart::set_data(const char* value) {
  
  data_.Set(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value),
              GetArenaNoVirtual());
  // @@protoc_insertion_point(field_set_char:content.ContentPart.data)
}
inline void ContentPart::set_data(const char* value,
    size_t size) {
  
  data_.Set(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(
      reinterpret_cast<const char*>(value), size), GetArenaNoVirtual());
  // @@protoc_insertion_point(field_set_pointer:content.ContentPart.data)
}
inline ::std::string* ContentPart::mutable_data() {
  
  // @@protoc_insertion_point(field_mutable:content.ContentPart.data)
  return data_.Mutable(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), GetArenaNoVirtual());
}
inline ::std::string* ContentPart::release_data() {
  
  return data_.Release(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), GetArenaNoVirtual());
}
inline ::std::string* ContentPart::unsafe_arena_release_data() {
  GOOGLE_DCHECK(GetArenaNoVirtual() != NULL);
  
  return data_.UnsafeArenaRelease(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      GetArenaNoVirtual());
}
inline void ContentPart::set_allocated_data(::std::string* data) {
  if (data != NULL) {
    
  } else {
    
  }
  data_.SetAllocated(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), data,
      GetArenaNoVirtual());
  // @@protoc_insertion_point(field_set_allocated:content.ContentPart.data)
}
inline void ContentPart::unsafe_arena_set_allocated_data(
    ::std::string* data) {
  GOOGLE_DCHECK(GetArenaNoVirtual() != NULL);
  if (data != NULL) {
    
  } else {
    
  }
  
  data_.UnsafeArenaSetAllocated(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      data, GetArenaNoVirtual());
  // @@protoc_insertion_point(field_set_allocated:content.ContentPart.data)
}

// -------------------------------------------------------------------

// Content

// optional .content.ContentData info = 1;
inline bool Content::has_info() const {
  return !_is_default_instance_ && info_ != NULL;
}
inline void Content::clear_info() {
  if (info_ != NULL) delete info_;
  info_ = NULL;
}
inline const ::content::ContentData& Content::info() const {
  // @@protoc_insertion_point(field_get:content.Content.info)
  return info_ != NULL ? *info_ : *default_instance_->info_;
}
inline ::content::ContentData* Content::mutable_info() {
  
  if (info_ == NULL) {
    info_ = ::google::protobuf::Arena::CreateMessage< ::content::ContentData >(
        GetArenaNoVirtual());
  }
  // @@protoc_insertion_point(field_mutable:content.Content.info)
  return info_;
}
inline ::content::ContentData* Content::release_info() {
  
  if (GetArenaNoVirtual() != NULL) {
    if (info_ == NULL) {
      return NULL;
    } else {
      ::content::ContentData* temp = new ::content::ContentData;
      temp->MergeFrom(*info_);
      info_ = NULL;
      return temp;
    }
  } else {
    ::content::ContentData* temp = info_;
    info_ = NULL;
    return temp;
  }
}
inline ::content::ContentData* Content::unsafe_arena_release_info() {
  
  ::content::ContentData* temp = info_;
  info_ = NULL;
  return temp;
}
inline void Content::set_allocated_info(::content::ContentData* info) {
  if (GetArenaNoVirtual() == NULL) {
    delete info_;
  }
  if (info != NULL) {
    if (GetArenaNoVirtual() != NULL && 
        ::google::protobuf::Arena::GetArena(info) == NULL) {
      GetArenaNoVirtual()->Own(info);
    } else if (GetArenaNoVirtual() !=
               ::google::protobuf::Arena::GetArena(info)) {
      ::content::ContentData* new_info = 
            ::google::protobuf::Arena::CreateMessage< ::content::ContentData >(
            GetArenaNoVirtual());
      new_info->CopyFrom(*info);
      info = new_info;
    }
  }
  info_ = info;
  if (info) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_set_allocated:content.Content.info)
}
inline void Content::unsafe_arena_set_allocated_info(
    ::content::ContentData* info) {
  if (GetArenaNoVirtual() == NULL) {
    delete info_;
  }
  info_ = info;
  if (info) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:content.Content.info)
}

// repeated .content.ContentPart parts = 2;
inline int Content::parts_size() const {
  return parts_.size();
}
inline void Content::clear_parts() {
  parts_.Clear();
}
inline const ::content::ContentPart& Content::parts(int index) const {
  // @@protoc_insertion_point(field_get:content.Content.parts)
  return parts_.Get(index);
}
inline ::content::ContentPart* Content::mutable_parts(int index) {
  // @@protoc_insertion_point(field_mutable:content.Content.parts)
  return parts_.Mutable(index);
}
inline ::content::ContentPart* Content::add_parts() {
  // @@protoc_insertion_point(field_add:content.Content.parts)
  return parts_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::content::ContentPart >&
Content::parts() const {
  // @@protoc_insertion_point(field_list:content.Content.parts)
  return parts_;
}
inline ::google::protobuf::RepeatedPtrField< ::content::ContentPart >*
Content::mutable_parts() {
  // @@protoc_insertion_point(field_mutable_list:content.Content.parts)
  return &parts_;
}

// -------------------------------------------------------------------

// CmdResponse

// optional string path = 1;
inline void CmdResponse::clear_path() {
  path_.ClearToEmpty(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), GetArenaNoVirtual());
}
inline const ::std::string& CmdResponse::path() const {
  // @@protoc_insertion_point(field_get:content.CmdResponse.path)
  return path_.Get(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void CmdResponse::set_path(const ::std::string& value) {
  
  path_.Set(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value, GetArenaNoVirtual());
  // @@protoc_insertion_point(field_set:content.CmdResponse.path)
}
inline void CmdResponse::set_path(const char* value) {
  
  path_.Set(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value),
              GetArenaNoVirtual());
  // @@protoc_insertion_point(field_set_char:content.CmdResponse.path)
}
inline void CmdResponse::set_path(const char* value,
    size_t size) {
  
  path_.Set(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(
      reinterpret_cast<const char*>(value), size), GetArenaNoVirtual());
  // @@protoc_insertion_point(field_set_pointer:content.CmdResponse.path)
}
inline ::std::string* CmdResponse::mutable_path() {
  
  // @@protoc_insertion_point(field_mutable:content.CmdResponse.path)
  return path_.Mutable(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), GetArenaNoVirtual());
}
inline ::std::string* CmdResponse::release_path() {
  
  return path_.Release(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), GetArenaNoVirtual());
}
inline ::std::string* CmdResponse::unsafe_arena_release_path() {
  GOOGLE_DCHECK(GetArenaNoVirtual() != NULL);
  
  return path_.UnsafeArenaRelease(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      GetArenaNoVirtual());
}
inline void CmdResponse::set_allocated_path(::std::string* path) {
  if (path != NULL) {
    
  } else {
    
  }
  path_.SetAllocated(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), path,
      GetArenaNoVirtual());
  // @@protoc_insertion_point(field_set_allocated:content.CmdResponse.path)
}
inline void CmdResponse::unsafe_arena_set_allocated_path(
    ::std::string* path) {
  GOOGLE_DCHECK(GetArenaNoVirtual() != NULL);
  if (path != NULL) {
    
  } else {
    
  }
  
  path_.UnsafeArenaSetAllocated(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      path, GetArenaNoVirtual());
  // @@protoc_insertion_point(field_set_allocated:content.CmdResponse.path)
}

// optional .content.Level level = 2;
inline void CmdResponse::clear_level() {
  level_ = 0;
}
inline ::content::Level CmdResponse::level() const {
  // @@protoc_insertion_point(field_get:content.CmdResponse.level)
  return static_cast< ::content::Level >(level_);
}
inline void CmdResponse::set_level(::content::Level value) {
  
  level_ = value;
  // @@protoc_insertion_point(field_set:content.CmdResponse.level)
}

// optional string msg = 3;
inline void CmdResponse::clear_msg() {
  msg_.ClearToEmpty(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), GetArenaNoVirtual());
}
inline const ::std::string& CmdResponse::msg() const {
  // @@protoc_insertion_point(field_get:content.CmdResponse.msg)
  return msg_.Get(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void CmdResponse::set_msg(const ::std::string& value) {
  
  msg_.Set(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value, GetArenaNoVirtual());
  // @@protoc_insertion_point(field_set:content.CmdResponse.msg)
}
inline void CmdResponse::set_msg(const char* value) {
  
  msg_.Set(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value),
              GetArenaNoVirtual());
  // @@protoc_insertion_point(field_set_char:content.CmdResponse.msg)
}
inline void CmdResponse::set_msg(const char* value,
    size_t size) {
  
  msg_.Set(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(
      reinterpret_cast<const char*>(value), size), GetArenaNoVirtual());
  // @@protoc_insertion_point(field_set_pointer:content.CmdResponse.msg)
}
inline ::std::string* CmdResponse::mutable_msg() {
  
  // @@protoc_insertion_point(field_mutable:content.CmdResponse.msg)
  return msg_.Mutable(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), GetArenaNoVirtual());
}
inline ::std::string* CmdResponse::release_msg() {
  
  return msg_.Release(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), GetArenaNoVirtual());
}
inline ::std::string* CmdResponse::unsafe_arena_release_msg() {
  GOOGLE_DCHECK(GetArenaNoVirtual() != NULL);
  
  return msg_.UnsafeArenaRelease(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      GetArenaNoVirtual());
}
inline void CmdResponse::set_allocated_msg(::std::string* msg) {
  if (msg != NULL) {
    
  } else {
    
  }
  msg_.SetAllocated(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), msg,
      GetArenaNoVirtual());
  // @@protoc_insertion_point(field_set_allocated:content.CmdResponse.msg)
}
inline void CmdResponse::unsafe_arena_set_allocated_msg(
    ::std::string* msg) {
  GOOGLE_DCHECK(GetArenaNoVirtual() != NULL);
  if (msg != NULL) {
    
  } else {
    
  }
  
  msg_.UnsafeArenaSetAllocated(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      msg, GetArenaNoVirtual());
  // @@protoc_insertion_point(field_set_allocated:content.CmdResponse.msg)
}

// -------------------------------------------------------------------

// UpdatePart

// optional .content.ContentPart part = 1;
inline bool UpdatePart::has_part() const {
  return !_is_default_instance_ && part_ != NULL;
}
inline void UpdatePart::clear_part() {
  if (part_ != NULL) delete part_;
  part_ = NULL;
}
inline const ::content::ContentPart& UpdatePart::part() const {
  // @@protoc_insertion_point(field_get:content.UpdatePart.part)
  return part_ != NULL ? *part_ : *default_instance_->part_;
}
inline ::content::ContentPart* UpdatePart::mutable_part() {
  
  if (part_ == NULL) {
    part_ = ::google::protobuf::Arena::CreateMessage< ::content::ContentPart >(
        GetArenaNoVirtual());
  }
  // @@protoc_insertion_point(field_mutable:content.UpdatePart.part)
  return part_;
}
inline ::content::ContentPart* UpdatePart::release_part() {
  
  if (GetArenaNoVirtual() != NULL) {
    if (part_ == NULL) {
      return NULL;
    } else {
      ::content::ContentPart* temp = new ::content::ContentPart;
      temp->MergeFrom(*part_);
      part_ = NULL;
      return temp;
    }
  } else {
    ::content::ContentPart* temp = part_;
    part_ = NULL;
    return temp;
  }
}
inline ::content::ContentPart* UpdatePart::unsafe_arena_release_part() {
  
  ::content::ContentPart* temp = part_;
  part_ = NULL;
  return temp;
}
inline void UpdatePart::set_allocated_part(::content::ContentPart* part) {
  if (GetArenaNoVirtual() == NULL) {
    delete part_;
  }
  if (part != NULL) {
    if (GetArenaNoVirtual() != NULL && 
        ::google::protobuf::Arena::GetArena(part) == NULL) {
      GetArenaNoVirtual()->Own(part);
    } else if (GetArenaNoVirtual() !=
               ::google::protobuf::Arena::GetArena(part)) {
      ::content::ContentPart* new_part = 
            ::google::protobuf::Arena::CreateMessage< ::content::ContentPart >(
            GetArenaNoVirtual());
      new_part->CopyFrom(*part);
      part = new_part;
    }
  }
  part_ = part;
  if (part) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_set_allocated:content.UpdatePart.part)
}
inline void UpdatePart::unsafe_arena_set_allocated_part(
    ::content::ContentPart* part) {
  if (GetArenaNoVirtual() == NULL) {
    delete part_;
  }
  part_ = part;
  if (part) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:content.UpdatePart.part)
}

// optional uint32 position = 2;
inline void UpdatePart::clear_position() {
  position_ = 0u;
}
inline ::google::protobuf::uint32 UpdatePart::position() const {
  // @@protoc_insertion_point(field_get:content.UpdatePart.position)
  return position_;
}
inline void UpdatePart::set_position(::google::protobuf::uint32 value) {
  
  position_ = value;
  // @@protoc_insertion_point(field_set:content.UpdatePart.position)
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace content

#ifndef SWIG
namespace google {
namespace protobuf {

template <> struct is_proto_enum< ::content::Format> : ::google::protobuf::internal::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::content::Format>() {
  return ::content::Format_descriptor();
}
template <> struct is_proto_enum< ::content::Level> : ::google::protobuf::internal::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::content::Level>() {
  return ::content::Level_descriptor();
}

}  // namespace protobuf
}  // namespace google
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_content_2eproto__INCLUDED
