// Generated by the gRPC protobuf plugin.
// If you make any local change, they will be lost.
// source: content.proto

#include "content.pb.h"
#include "content.grpc.pb.h"

#include <grpc++/async_unary_call.h>
#include <grpc++/channel_interface.h>
#include <grpc++/impl/client_unary_call.h>
#include <grpc++/impl/rpc_service_method.h>
#include <grpc++/impl/service_type.h>
#include <grpc++/stream.h>
namespace content {

static const char* ContentCmdHandler_method_names[] = {
  "/content.ContentCmdHandler/save",
  "/content.ContentCmdHandler/remove",
  "/content.ContentCmdHandler/removePart",
  "/content.ContentCmdHandler/updatePart",
};

std::unique_ptr< ContentCmdHandler::Stub> ContentCmdHandler::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel) {
  std::unique_ptr< ContentCmdHandler::Stub> stub(new ContentCmdHandler::Stub(channel));
  return stub;
}

ContentCmdHandler::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel)
  : ::grpc::InternalStub(channel), rpcmethod_save_(ContentCmdHandler_method_names[0], ::grpc::RpcMethod::NORMAL_RPC, channel->RegisterMethod(ContentCmdHandler_method_names[0]))
  , rpcmethod_remove_(ContentCmdHandler_method_names[1], ::grpc::RpcMethod::NORMAL_RPC, channel->RegisterMethod(ContentCmdHandler_method_names[1]))
  , rpcmethod_removePart_(ContentCmdHandler_method_names[2], ::grpc::RpcMethod::NORMAL_RPC, channel->RegisterMethod(ContentCmdHandler_method_names[2]))
  , rpcmethod_updatePart_(ContentCmdHandler_method_names[3], ::grpc::RpcMethod::NORMAL_RPC, channel->RegisterMethod(ContentCmdHandler_method_names[3]))
  {}

::grpc::Status ContentCmdHandler::Stub::save(::grpc::ClientContext* context, const ::content::Content& request, ::content::CmdResponse* response) {
  return ::grpc::BlockingUnaryCall(channel(), rpcmethod_save_, context, request, response);
}

std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::content::CmdResponse>> ContentCmdHandler::Stub::Asyncsave(::grpc::ClientContext* context, const ::content::Content& request, ::grpc::CompletionQueue* cq, void* tag) {
  return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::content::CmdResponse>>(new ::grpc::ClientAsyncResponseReader< ::content::CmdResponse>(channel(), cq, rpcmethod_save_, context, request, tag));
}

::grpc::Status ContentCmdHandler::Stub::remove(::grpc::ClientContext* context, const ::content::Uuid& request, ::content::CmdResponse* response) {
  return ::grpc::BlockingUnaryCall(channel(), rpcmethod_remove_, context, request, response);
}

std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::content::CmdResponse>> ContentCmdHandler::Stub::Asyncremove(::grpc::ClientContext* context, const ::content::Uuid& request, ::grpc::CompletionQueue* cq, void* tag) {
  return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::content::CmdResponse>>(new ::grpc::ClientAsyncResponseReader< ::content::CmdResponse>(channel(), cq, rpcmethod_remove_, context, request, tag));
}

::grpc::Status ContentCmdHandler::Stub::removePart(::grpc::ClientContext* context, const ::content::Uuid& request, ::content::CmdResponse* response) {
  return ::grpc::BlockingUnaryCall(channel(), rpcmethod_removePart_, context, request, response);
}

std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::content::CmdResponse>> ContentCmdHandler::Stub::AsyncremovePart(::grpc::ClientContext* context, const ::content::Uuid& request, ::grpc::CompletionQueue* cq, void* tag) {
  return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::content::CmdResponse>>(new ::grpc::ClientAsyncResponseReader< ::content::CmdResponse>(channel(), cq, rpcmethod_removePart_, context, request, tag));
}

::grpc::Status ContentCmdHandler::Stub::updatePart(::grpc::ClientContext* context, const ::content::UpdatePart& request, ::content::CmdResponse* response) {
  return ::grpc::BlockingUnaryCall(channel(), rpcmethod_updatePart_, context, request, response);
}

std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::content::CmdResponse>> ContentCmdHandler::Stub::AsyncupdatePart(::grpc::ClientContext* context, const ::content::UpdatePart& request, ::grpc::CompletionQueue* cq, void* tag) {
  return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::content::CmdResponse>>(new ::grpc::ClientAsyncResponseReader< ::content::CmdResponse>(channel(), cq, rpcmethod_updatePart_, context, request, tag));
}

ContentCmdHandler::AsyncService::AsyncService(::grpc::CompletionQueue* cq) : ::grpc::AsynchronousService(cq, ContentCmdHandler_method_names, 4) {}

ContentCmdHandler::Service::~Service() {
  delete service_;
}

::grpc::Status ContentCmdHandler::Service::save(::grpc::ServerContext* context, const ::content::Content* request, ::content::CmdResponse* response) {
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED);
}

void ContentCmdHandler::AsyncService::Requestsave(::grpc::ServerContext* context, ::content::Content* request, ::grpc::ServerAsyncResponseWriter< ::content::CmdResponse>* response, ::grpc::CompletionQueue* cq, void* tag) {
  AsynchronousService::RequestAsyncUnary(0, context, request, response, cq, tag);
}

::grpc::Status ContentCmdHandler::Service::remove(::grpc::ServerContext* context, const ::content::Uuid* request, ::content::CmdResponse* response) {
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED);
}

void ContentCmdHandler::AsyncService::Requestremove(::grpc::ServerContext* context, ::content::Uuid* request, ::grpc::ServerAsyncResponseWriter< ::content::CmdResponse>* response, ::grpc::CompletionQueue* cq, void* tag) {
  AsynchronousService::RequestAsyncUnary(1, context, request, response, cq, tag);
}

::grpc::Status ContentCmdHandler::Service::removePart(::grpc::ServerContext* context, const ::content::Uuid* request, ::content::CmdResponse* response) {
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED);
}

void ContentCmdHandler::AsyncService::RequestremovePart(::grpc::ServerContext* context, ::content::Uuid* request, ::grpc::ServerAsyncResponseWriter< ::content::CmdResponse>* response, ::grpc::CompletionQueue* cq, void* tag) {
  AsynchronousService::RequestAsyncUnary(2, context, request, response, cq, tag);
}

::grpc::Status ContentCmdHandler::Service::updatePart(::grpc::ServerContext* context, const ::content::UpdatePart* request, ::content::CmdResponse* response) {
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED);
}

void ContentCmdHandler::AsyncService::RequestupdatePart(::grpc::ServerContext* context, ::content::UpdatePart* request, ::grpc::ServerAsyncResponseWriter< ::content::CmdResponse>* response, ::grpc::CompletionQueue* cq, void* tag) {
  AsynchronousService::RequestAsyncUnary(3, context, request, response, cq, tag);
}

::grpc::RpcService* ContentCmdHandler::Service::service() {
  if (service_ != nullptr) {
    return service_;
  }
  service_ = new ::grpc::RpcService();
  service_->AddMethod(new ::grpc::RpcServiceMethod(
      ContentCmdHandler_method_names[0],
      ::grpc::RpcMethod::NORMAL_RPC,
      new ::grpc::RpcMethodHandler< ContentCmdHandler::Service, ::content::Content, ::content::CmdResponse>(
          std::mem_fn(&ContentCmdHandler::Service::save), this),
      new ::content::Content, new ::content::CmdResponse));
  service_->AddMethod(new ::grpc::RpcServiceMethod(
      ContentCmdHandler_method_names[1],
      ::grpc::RpcMethod::NORMAL_RPC,
      new ::grpc::RpcMethodHandler< ContentCmdHandler::Service, ::content::Uuid, ::content::CmdResponse>(
          std::mem_fn(&ContentCmdHandler::Service::remove), this),
      new ::content::Uuid, new ::content::CmdResponse));
  service_->AddMethod(new ::grpc::RpcServiceMethod(
      ContentCmdHandler_method_names[2],
      ::grpc::RpcMethod::NORMAL_RPC,
      new ::grpc::RpcMethodHandler< ContentCmdHandler::Service, ::content::Uuid, ::content::CmdResponse>(
          std::mem_fn(&ContentCmdHandler::Service::removePart), this),
      new ::content::Uuid, new ::content::CmdResponse));
  service_->AddMethod(new ::grpc::RpcServiceMethod(
      ContentCmdHandler_method_names[3],
      ::grpc::RpcMethod::NORMAL_RPC,
      new ::grpc::RpcMethodHandler< ContentCmdHandler::Service, ::content::UpdatePart, ::content::CmdResponse>(
          std::mem_fn(&ContentCmdHandler::Service::updatePart), this),
      new ::content::UpdatePart, new ::content::CmdResponse));
  return service_;
}


}  // namespace content

